### ISSUE TITLE
Pierre doesn't attempt to join the channel you specify.

### ISSUE THREAD

**Issue by DmytryEmery** [mthjones/pierre#6]
If you specify a channel in the .pierre_config which pierre has not joined, you get an error from pierre.

Maybe he should attempt to join?

very minor, possibly ignore if he will send private messages in the future?

**Comment by mthjones** [comment]
Good idea! Should be pretty simple as well with the Slack library: [`channels::join`](http://bentheelder.github.io/slack-rs/slack/api/channels/fn.join.html). Assuming you can make the call multiple times without it failing.

**Comment by DmytryEmery** [comment]
https://github.com/slackhq/node-slack-client/issues/26#issuecomment-76102843

Bots can only be invited to channels.

I guess this is over :(
